INSERT INTO frontend_templates (template_key, template_name, is_active, template_config_json)
SELECT
  'silver-scan-dark',
  'Silver Scan Dark',
  0,
  '{"page_title":"Cek Keaslian Produk","page_description":"Tampilan verifikasi dark mode dengan scanner kamera dua kolom.","home_eyebrow":"%company% Scanner Gateway","home_title":"Scan Produk dengan Dark Mode","home_lead":"Klik panel scanner di kiri untuk membuka kamera, lalu arahkan ke barcode produk. Jika perlu, masukkan kode secara manual di sisi kanan.","home_search_eyebrow":"Manual Verification","home_search_meta":"Gunakan input di bawah jika ingin mengetik kode secara langsung tanpa kamera.","home_placeholder":"Masukkan kode produk","home_button_label":"Cek Produk","home_specimen_subtype":"authenticity","home_specimen_type":"Registered Product","home_specimen_grade":"Official Verification","home_specimen_weight":"Trusted Registry","home_specimen_serial":"Scan Your Code","verified_eyebrow":"Authenticity Confirmed","verified_title":"Produk Terverifikasi","verified_lead":"Selamat, kode %code% berhasil dicocokkan dengan data resmi %company%.","verified_meta":"Informasi ini menjamin bahwa produk Anda telah terdaftar secara resmi di %company%.","verified_label_code":"Kode Produk","verified_label_category":"Kategori Produk","verified_label_weight":"Berat","verified_label_date":"Tanggal Produksi","verified_back_button_label":"Cek Kode Lain","invalid_eyebrow":"Authenticity Failed","invalid_title":"Kode Tidak Valid","invalid_serial":"%company%","invalid_lead":"Kode produk tidak ditemukan pada database resmi. Pastikan Anda memasukkan kode dengan benar sebelum melanjutkan pengecekan ulang.","invalid_meta":"Silakan coba lagi atau hubungi layanan pelanggan untuk bantuan lebih lanjut.","invalid_label_status":"Status","invalid_label_product":"Produk","invalid_label_action":"Tindakan","invalid_detail_status_value":"Tidak Ditemukan","invalid_detail_product_value":"Belum Terverifikasi","invalid_detail_action_value":"Periksa Kode Ulang","invalid_back_button_label":"Ulangi atau cek kode baru","footer_note":"Tampilan dark mode dengan scanner kamera.","home_scanner_button_label":"Launch Scanner","home_scanner_hint":"Klik ikon scanner untuk membuka kamera.","home_scanner_modal_title":"QR Scanner","home_scanner_modal_close_label":"Close Scanner","home_scanner_status_ready":"Siap memindai barcode.","home_scanner_status_scanning":"Memindai barcode...","home_scanner_status_unsupported":"Scanner kamera tidak didukung di browser ini.","home_scanner_status_denied":"Akses kamera ditolak.","home_scanner_status_found":"Kode ditemukan, membuka verifikasi."}'
WHERE NOT EXISTS (
  SELECT 1
  FROM frontend_templates
  WHERE template_key = 'silver-scan-dark'
);
